name: C++ Build and Test

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests

jobs:
  build:
    runs-on: ubuntu-latest  # You can use other OS types too like windows-latest or macos-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up C++ Compiler
      uses: actions/setup-cpp@v1  # This is the correct setup for C++ on GitHub Actions
      with:
        compiler: 'gcc'  # You can specify 'clang' as well
    
    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..
        make  # Build the C++ project

    - name: Run tests
      run: |
        cd build
        ./tests  # Run your test cases or executable
