name: C++ Build and Test

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up C++ Compiler
      uses: actions/setup-toolchain@v1  # Use setup-toolchain for C++ environment
      with:
        toolchain: 'gcc'  # You can specify a specific toolchain like 'gcc' or 'clang'
    
    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..
        make  # Build the C++ project

    - name: Run tests
      run: |
        cd build
        ./tests  # Run your test cases or executable
