name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up C++ Compiler (GCC)
      run: |
        sudo apt update
        sudo apt install -y g++ cmake build-essential

    - name: Show CMake Version
      run: cmake --version  # Add this to check if CMake is correctly installed

    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..  # Check for errors here
        make VERBOSE=1  # This will provide more detailed output from make

    - name: Run tests
      run: |
        cd build
        ./tests  # Or your executable
