name: C++ Build and Test

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up C++ Compiler (GCC)
      run: |
        sudo apt update
        sudo apt install -y g++ cmake build-essential  # Install GCC, CMake, and build essentials
    
    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..
        make  # Build the C++ project

    - name: Run tests
      run: |
        cd build
        ./tests  # Run your test cases or executable
